[package]
name = "bonsai_lang_javascript"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "JavaScript language adapter."

[dependencies]
bonsai_common = { workspace = true }
bonsai_lang_api = { workspace = true }
tree-sitter = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
bonsai_conformance = { workspace = true }
bonsai_db = { workspace = true }
bonsai_testkit = { workspace = true }
bonsai_vfs = { workspace = true }
