[package]
name = "bonsai-ninja-lang-cpp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
description = "C++ language adapter."

[lib]
name = "bonsai_lang_cpp"
path = "src/lib.rs"

[dependencies]
bonsai_common = { workspace = true }
bonsai_lang_api = { workspace = true }
tree-sitter = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
bonsai_conformance = { package = "bonsai-ninja-conformance", path = "../conformance" }
bonsai_diagnostics = { package = "bonsai-ninja-diagnostics", path = "../diagnostics" }
bonsai_vfs = { package = "bonsai-ninja-vfs", path = "../vfs" }
parking_lot = { workspace = true }
