[package]
name = "bonsai-ninja-index"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
description = "Declaration and reference indices."

[lib]
name = "bonsai_index"
path = "src/lib.rs"

[dependencies]
bonsai_common = { workspace = true }
bonsai_lang_api = { workspace = true }
ahash = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
