[package]
name = "bonsai_lang_dart"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Dart language adapter."

[dependencies]
bonsai_common = { workspace = true }
bonsai_lang_api = { workspace = true }
tree-sitter = { workspace = true }

[lints]
workspace = true
