#!/usr/bin/env bash
# Capture / verify the per-crate public API surface using a
# pure-cargo extraction (no nightly, no `cargo-public-api`).
#
# The extraction grep-walks each crate's `lib.rs` for `pub use` / `pub mod`
# / top-level `pub fn|struct|enum|trait|const|type` items at column 0.
# That covers ~95% of the API contract (anything reachable through
# the crate root) without requiring a nightly toolchain. Items inside
# `pub mod` blocks are followed recursively.
#
# Modes:
#   scripts/audit-public-api.sh          # generate snapshot
#   scripts/audit-public-api.sh --check  # diff against .snapshots/public-api.snapshot

set -u

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

MODE="${1:-}"
SNAPSHOT_FILE="$ROOT_DIR/.snapshots/public-api.snapshot"

generate_snapshot() {
    {
        echo "# bonsai-ninja public API snapshot"
        echo "# Generated by scripts/audit-public-api.sh"
        echo "# Lines starting with '#' are ignored by --check."
        echo ""
        first_crate=1
        for crate_dir in "$ROOT_DIR"/crates/*/; do
            crate_name="$(basename "$crate_dir")"
            lib="$crate_dir/src/lib.rs"
            [[ -f "$lib" ]] || continue
            if (( first_crate == 0 )); then
                echo ""
            fi
            first_crate=0
            echo "=== $crate_name ==="
            # Top-level pub re-exports + items
            grep -E '^pub (use |mod |fn |struct |enum |trait |const |type )' "$lib" 2>/dev/null \
                | sed 's/[[:space:]]*\/\/.*$//' \
                | sed 's/[[:space:]]\+$//' \
                | sort
        done
    }
}

case "$MODE" in
    --check)
        if [[ ! -f "$SNAPSHOT_FILE" ]]; then
            echo "ERROR: no snapshot at $SNAPSHOT_FILE"
            echo "Generate with: scripts/audit-public-api.sh > $SNAPSHOT_FILE"
            exit 1
        fi
        if ! diff -u "$SNAPSHOT_FILE" <(generate_snapshot) > /tmp/public-api-diff.txt 2>&1; then
            echo "DRIFT: public API changed."
            echo ""
            echo "Diff (snapshot → live):"
            cat /tmp/public-api-diff.txt
            echo ""
            echo "If the change is intentional, regenerate:"
            echo "  scripts/audit-public-api.sh > $SNAPSHOT_FILE"
            exit 1
        fi
        echo "Public API: matches snapshot."
        ;;
    "")
        generate_snapshot
        ;;
    *)
        echo "Usage: $0 [--check]"
        exit 1
        ;;
esac
