[package]
name = "bonsai_db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Incremental analyzer database."

[dependencies]
bonsai_common = { workspace = true }
bonsai_diagnostics = { workspace = true }
bonsai_factstore = { workspace = true }
bonsai_hash = { workspace = true }
bonsai_vfs = { workspace = true }
bonsai_parser = { workspace = true }
bonsai_lang_api = { workspace = true }
bonsai_index = { workspace = true }
bonsai_cfg = { workspace = true }
bonsai_abstract_interp = { workspace = true }
bonsai_trace = { workspace = true }
bonsai_idg = { workspace = true }
parking_lot = { workspace = true }
lru = { workspace = true }
ahash = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
zstd = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
bonsai_lang_python = { workspace = true }
tree-sitter = { workspace = true }

[lints]
workspace = true
