[package]
name = "bonsai_resolve"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Module and name resolution."

[dependencies]
bonsai_common = { workspace = true }
bonsai_index = { workspace = true }
bonsai_lang_api = { workspace = true }
ahash = { workspace = true }

[lints]
workspace = true
