[package]
name = "bonsai-ninja-resolve"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
description = "Module and name resolution."

[lib]
name = "bonsai_resolve"
path = "src/lib.rs"

[dependencies]
bonsai_common = { workspace = true }
bonsai_index = { workspace = true }
bonsai_lang_api = { workspace = true }
ahash = { workspace = true }

[lints]
workspace = true
