[package]
name = "bonsai_workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Top-level workspace container + public library API."

[dependencies]
bonsai_common = { workspace = true }
bonsai_hash = { workspace = true }
bonsai_diagnostics = { workspace = true }
bonsai_vfs = { workspace = true }
bonsai_lang_api = { workspace = true }
bonsai_index = { workspace = true }
bonsai_db = { workspace = true }
bonsai_trace = { workspace = true }
bonsai_abstract_interp = { workspace = true }
bonsai_callgraph = { workspace = true }
bonsai_resolve = { workspace = true }
bonsai_taint = { workspace = true }
bonsai_factstore = { workspace = true }
bonsai_idg = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
ahash = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
ignore = { workspace = true }
fs2 = { workspace = true }
lru = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
bonsai_trace = { workspace = true }
bonsai_lang_c = { workspace = true }
bonsai_lang_cpp = { workspace = true }
bonsai_lang_csharp = { workspace = true }
bonsai_lang_scala = { workspace = true }
bonsai_lang_rust = { workspace = true }
bonsai_lang_go = { workspace = true }
bonsai_lang_java = { workspace = true }
bonsai_lang_kotlin = { workspace = true }
bonsai_lang_swift = { workspace = true }
bonsai_lang_javascript = { workspace = true }
bonsai_lang_typescript = { workspace = true }
bonsai_lang_php = { workspace = true }
bonsai_lang_python = { workspace = true }
bonsai_lang_perl = { workspace = true }
bonsai_lang_ruby = { workspace = true }
bonsai_lang_dart = { workspace = true }
bonsai_lang_objc = { workspace = true }
bonsai_lang_lua = { workspace = true }
bonsai_lang_elixir = { workspace = true }
bonsai_lang_erlang = { workspace = true }
regex = { workspace = true }

[lints]
workspace = true
